// One owner for the supervision-branch pre-branch classifier core, shared by
// the Pi supervision-branch extension (.pi/extensions/fm-branch-supervision.ts)
// and the Claude Code supervision-branch mod
// (.claude/mods/fm-branch-mod/hooks/branch.ts).
//
// This module owns, once: the evidence-bundle byte-range parse of
// bin/fm-wake-evidence.sh output and its failure text, the classifier prompt
// construction, the model-answer interpretation rule (verdict whitelist,
// unparsed and failed-call fallbacks), the durable classification-log record
// shape and its serialization, and the classifier-pass covering-outcome rule
// (the "Passed to main directly (...)" summary, its append argv, and the
// bare evidence gatherer that advances a task's classifier offset).
//
// Host seams - declared, deliberately not unified:
//   - THE MODEL CALL. The mod calls $.model.complete; the Pi extension
//     resolves the configured model name against its isolated runtime and
//     calls pi-ai's completeSimple. Both receive the same request object
//     ({model, system, prompt, maxTokens}) and return the answer text; a
//     rejection is a failed call and routes the wake to main.
//   - SCRIPT SPAWNS. The host binds cwd and environment; this module builds
//     the argv (bash, the script under paths.bin, its arguments) and owns
//     the timeouts.
//   - FILE READS AND APPENDS. The host reads the classifier system prompt
//     (paths differ per host) and the model config, and appends the
//     serialized record line to state/branch-mod-classifications.jsonl with
//     its own rotation and failure logging.
//   - THE CLOCK is injected, so tests pin record bytes without waiting.
//
// The mod does not import this file directly: its hooks validator refuses
// anything but relative imports and "claude-code", so the mod consumes a
// byte-identical vendored copy regenerated by bin/fm-branch-shared-sync.sh.
// This file must therefore stay dependency-free: no imports of any kind.

/** One task's bash-gathered evidence bundle: the status byte range the bundle
 * covers (both -1 when the gatherer named no range) and the bundle text. */
export interface ClassifierEvidence {
  task: string;
  from: number;
  to: number;
  text: string;
}

/** The classifier's verdict for one wake. Anything outside the whitelist is
 * reported as "uncertain" so an unexpected answer passes the wake to main. */
export const CLASSIFIER_VERDICTS = ["routine", "captain", "uncertain"];

export const CLASSIFIER_MAX_TOKENS = 200;
/** bin/fm-wake-evidence.sh per-task timeout, as the mod has always run it. */
export const CLASSIFIER_EVIDENCE_TIMEOUT_MS = 25_000;
/** The durable record keeps at most this many characters of the raw answer. */
export const CLASSIFIER_ANSWER_CAP = 400;

export interface ClassifierResult {
  verdict: string;
  reason: string;
  ms: number;
  promptChars: number;
  answer: string;
  model: string;
  evidence: ClassifierEvidence[];
}

export interface ClassifierRecord {
  t: string;
  wake: string;
  tasks: string[];
  seqs: string[];
  evidence: Array<{ task: string; from: number; to: number }>;
  verdict: string;
  reason: string;
  model: string;
  ms: number;
  answer: string;
}

/** The host surface the classifier runs against. runScript binds the host's
 * cwd and environment; readFile/readClassifierModel are the host's own
 * config reads (missing config falls back host-side). */
export interface ClassifierDeps {
  paths: { bin: string };
  runScript(argv: string[], opts: { timeoutMs: number }): Promise<{ exitCode: number; stdout: string; stderr: string }>;
  readSystemPrompt(): Promise<string>;
  readClassifierModel(): Promise<string>;
  complete(req: { model: string; system: string; prompt: string; maxTokens: number }): Promise<string>;
  clock: { now(): number; iso(): string };
}

// The classifier system prompt is read once per module lifetime, exactly as
// each host memoized it before this extraction.
let cachedSystemPrompt: string | null = null;

/** Behavior-neutral test seam: clears the memoized system prompt. */
export function __resetClassifierSystemPrompt(): void {
  cachedSystemPrompt = null;
}

async function classifierSystemPrompt(deps: ClassifierDeps): Promise<string> {
  if (!cachedSystemPrompt) cachedSystemPrompt = await deps.readSystemPrompt();
  return cachedSystemPrompt;
}

/** The "## task <task> status bytes <from>-<to>" first-line parse. Returns
 * null when the bundle names no range. */
export function evidenceStatusRange(stdout: string): { from: number; to: number } | null {
  const m = stdout.match(/status bytes ([0-9]+)-([0-9]+)/);
  return m ? { from: Number(m[1]), to: Number(m[2]) } : null;
}

/** The evidence text a failed gatherer contributes to the prompt, so a
 * failed gather is judgeable evidence rather than a silent gap. */
export function evidenceFailureBundle(task: string, stderr: string): string {
  return `## task ${task}\n(evidence gatherer failed: ${String(stderr).slice(0, 300)})`;
}

/** One task's evidence bundle through bin/fm-wake-evidence.sh. */
export async function gatherClassifierEvidence(deps: ClassifierDeps, task: string): Promise<ClassifierEvidence> {
  const r = await deps.runScript(["bash", `${deps.paths.bin}/fm-wake-evidence.sh`, task], {
    timeoutMs: CLASSIFIER_EVIDENCE_TIMEOUT_MS,
  });
  if (r.exitCode !== 0) return { task, from: -1, to: -1, text: evidenceFailureBundle(task, r.stderr) };
  const range = evidenceStatusRange(r.stdout);
  return { task, from: range ? range.from : -1, to: range ? range.to : -1, text: r.stdout };
}

/** The user prompt of a classifier call, byte-stable: the wake text, the
 * evidence bundles in task order, and the one-JSON-line instruction. */
export function buildClassifierPrompt(wake: string, evidence: ClassifierEvidence[]): string {
  return `WAKE:\n${wake}\n\nEVIDENCE (bash-gathered, read-only):\n\n${evidence.map((b) => b.text).join("\n")}\n\nAnswer with the one JSON line.`;
}

/** The model-answer rule, stated once: a failed call or a malformed answer is
 * verdict "uncertain" (the wake goes to main); a whitelisted verdict is
 * trusted and every answer's reason string is carried through. */
export function interpretClassifierAnswer(answer: string, completeError: string | null): { verdict: string; reason: string } {
  let verdict = "uncertain";
  let why = completeError !== null ? `model.complete failed: ${completeError}` : "unparsed";
  const s = answer.indexOf("{");
  const e = answer.lastIndexOf("}");
  if (s >= 0 && e > s) {
    try {
      const j = JSON.parse(answer.slice(s, e + 1));
      if (CLASSIFIER_VERDICTS.includes(j.verdict)) verdict = j.verdict;
      why = String(j.reason ?? "");
    } catch {
      why = "unparsed";
    }
  }
  return { verdict, reason: why };
}

/** The covering summary a classifier pass writes into the outcome store, so
 * the branch's next wake note and the drain backstop read main's direct
 * handling as covered. The shadow module's provenance test matches the same
 * prefix. */
export function passedToMainSummary(why: string, classifierReason: string): string {
  return `Passed to main directly (${why}): ${classifierReason}`;
}

/** The store append argv of one classifier-pass covering row. */
export function classifierPassCoverArgv(task: string, summary: string, wake: string): string[] {
  return ["append", "--task", task, "--verdict", "captain", "--summary", summary, "--silent", "false", "--wake", wake];
}

/** The durable classification-log record, field order pinned: the scorers
 * (bin/fm-branch-classifier-score.sh) parse it, and byte-stability keeps the
 * log diffable across refactors. */
export function buildClassifierRecord(input: {
  clock: { iso(): string };
  wake: string;
  tasks: string[];
  seqs: string[];
  evidence: ClassifierEvidence[];
  result: ClassifierResult;
}): ClassifierRecord {
  return {
    t: input.clock.iso(),
    wake: input.wake,
    tasks: input.tasks,
    seqs: input.seqs,
    evidence: input.evidence.map((b) => ({ task: b.task, from: b.from, to: b.to })),
    verdict: input.result.verdict,
    reason: input.result.reason,
    model: input.result.model,
    ms: input.result.ms,
    answer: input.result.answer,
  };
}

/** One JSON line plus newline, ready for the host's size-capped append. */
export function serializeClassifierRecord(record: ClassifierRecord): string {
  return `${JSON.stringify(record)}\n`;
}

export interface ClassifyOutcome {
  result: ClassifierResult;
  record: ClassifierRecord;
  recordLine: string;
}

/** The classifier ahead of the branch: gather each task's evidence bundle,
 * ask the configured model, and return the verdict plus the exact durable
 * record. The host appends recordLine to its classification log. */
export async function classifyWake(deps: ClassifierDeps, input: { wake: string; tasks: string[]; seqs: string[] }): Promise<ClassifyOutcome> {
  const system = await classifierSystemPrompt(deps);
  const evidence: ClassifierEvidence[] = [];
  for (const task of input.tasks) evidence.push(await gatherClassifierEvidence(deps, task));
  const prompt = buildClassifierPrompt(input.wake, evidence);
  const model = await deps.readClassifierModel();
  const t0 = deps.clock.now();
  let answer = "";
  let completeError: string | null = null;
  try {
    answer = String(await deps.complete({ model, system, prompt, maxTokens: CLASSIFIER_MAX_TOKENS }));
  } catch (error) {
    completeError = String(error);
  }
  const parsed = interpretClassifierAnswer(answer, completeError);
  const result: ClassifierResult = {
    verdict: parsed.verdict,
    reason: parsed.reason,
    ms: deps.clock.now() - t0,
    promptChars: prompt.length + system.length,
    answer: answer.slice(0, CLASSIFIER_ANSWER_CAP),
    model,
    evidence,
  };
  const record = buildClassifierRecord({ clock: deps.clock, wake: input.wake, tasks: input.tasks, seqs: input.seqs, evidence, result });
  return { result, record, recordLine: serializeClassifierRecord(record) };
}
