// fm-branch-mod: the firstmate supervision branch as a Claude Code hooks module,
// with one persistent branch agent per session and a text-only classifier ahead
// of it. docs/claude-supervision-branch.md owns the operator contract; this
// header owns the module's own shape.
//
//   (a) prompt.submit: the Stop-hook rewake (or the continuity monitor's event)
//       -> eligibility scope -> classifier -> grant -> deliver to the branch
//       -> drop. Delivery is $.agent.spawn once per branch generation, then
//       $.tool.call SendMessage to the same named agent for every later wake.
//   (b) agents/fm-branch.md: bin/fm-branch-prompt.sh plus the hooks-module
//       addendum, generated by bin/fm-branch-agent-md.sh.
//   (c) tool.call rewrite injecting the branch actor identity into Bash.
//   (d) fm_branch_report / fm_branch_processed backed by bin/fm-branch-outcome.sh.
//   (e) turn.complete (branch): release grant, context-bound rotation, the
//       deterministic backstop (bin/fm-wake-evidence.sh --routine-covered) as a
//       main prompt, then route any wake still queued.
//   (f) turn.step effort rewrite for the branch's own agent ids.
//   continuity: one Monitor task per session streams each watcher close as a
//       task-notification into prompt.submit; armed at session start when the
//       mode file is present and the session lock is held, on any captain
//       prompt or stop-hook-sourced wake that finds no live monitor (a claim
//       older than MONITOR_CLAIM_STALE_MS counts as dead), and from the
//       branch's settlement - never dependent on a captain prompt to exist.
//
// The module refuses to load on any Claude Code version other than CLAUDE_CODE_PIN:
// the version is read from the binary hosting the session (PATH `claude` is only
// the fallback), every hook passes through untouched on a mismatch, and the
// session runs as if the plugin were absent.
//
// Switch (a file under the home's state directory):
//   .branch-mod-mode        present = route wakes; absent = log only, never route.
//                           The same presence switches every bin/ piece the mod relies on.
// Records (same directory):
//   .branch-mod-counters            session counters keyed by the lock pid
//   .branch-mod-passed              queue seqs passed to main with a cover row and not yet acknowledged
//   branch-mod-events.jsonl         append-only event log, size-capped
//   branch-mod-classifications.jsonl  one record per classifier call
//   branch-mod-shadow.jsonl         one record per shadow advisory call (config/classifier-shadow = jev), size-capped
import type { On } from 'claude-code'
// The shared v8 fold and eligible-rows scan, vendored by
// bin/fm-branch-shared-sync.sh (the source's node:fs default bindings are
// excluded: this module may import only its own files and "claude-code").
import {
  foldVocabularyFromEnv,
  hasOpenNeedsDecision,
  scopeForUnreadWake as libScopeForUnreadWake,
  statusKindFromMetaText,
} from '../lib/fm-branch-eligibility.ts'
import type { DecisionVerdictCache, FoldVocabulary, QueueMeta, StatusStat, StatusText } from '../lib/fm-branch-eligibility.ts'
import {
  appendFailureMessage,
  markProcessedArgv,
  markReadArgv,
  reportAppendArgv,
  reportSuccessMessage,
  reportTaskScopeVerdict,
  runSettlementStep,
  validateBranchReport,
  validateThroughValue,
} from '../lib/fm-branch-report-sequence.ts'
import {
  classifierPassCoverArgv,
  classifyWake,
  passedToMainSummary,
  type ClassifierEvidence,
  type ClassifierResult,
} from '../lib/fm-branch-classifier.ts'
import { runShadowAdvisory as libRunShadowAdvisory } from '../lib/fm-branch-shadow.ts'
import { createProviderErrorLatch } from '../lib/fm-branch-provider-latch.ts'

export const CLAUDE_CODE_PIN = '2.1.278'

type Scope = {
  status: 'safe' | 'empty' | 'unsafe'
  eligible: boolean
  eligibleSeqs: string[]
  // Durable wake identity: the wake-queue "epoch:seq" of every eligible row,
  // comma-joined. Stamped onto shadow records and onto the outcome row the
  // branch reports for this wake, so retrospective scorers join by identity
  // instead of agent-supplied wake text.
  eligibleWakeKey: string
  eligibleTasks: string[]
  corrupted: boolean
  needsDecisionTasks: string[]
  allSeqs?: string[]
}

type InFlight = {
  seqs: string[]
  wakeKey: string
  tasks: Set<string>
  heartbeat: boolean
  wakeText: string
  reason: string
  reportedSeqs: number[]
  startedAt: number
  granted: boolean
  wakeNo: number
  via: 'spawn' | 'send'
}

const PLUGIN = 'fm-branch-mod'
const BRANCH_NAME = 'fm-branch'
const REPORT_TOOL = `mcp__${PLUGIN}__fm_branch_report`
const PROCESSED_TOOL = `mcp__${PLUGIN}__fm_branch_processed`
const PROVIDER_ERROR_LATCH_POLICY = {
  threshold: 2,
  baseCooldownMs: 5 * 60 * 1000,
  maxCooldownMs: 5 * 60 * 1000,
  recoveryProbe: false,
}
// The branch is bounded inside the mod: once a wake's per-step request context
// (the turn's summed usage over its steps) passes this many tokens, the next
// wake goes to a fresh agent seeded with the index note.
const BRANCH_ROTATE_TOKENS = 60_000
const MONITOR_DESCRIPTION = 'fm-branch-mod watcher continuity'
const MONITOR_TIMEOUT_MS = 30 * 60 * 1000
// An armed claim older than this with no expiry notice in hand is a dead
// monitor whose notice was lost: the claim expires and the next arm site arms.
const MONITOR_CLAIM_STALE_MS = MONITOR_TIMEOUT_MS + 5 * 60 * 1000
const EVENT_LOG_CAP_BYTES = 4_000_000
const PASSED_DEDUPE_MS = 90_000
const INFLIGHT_STALE_MS = 180_000
const BOAT = '⛵'
const ANCHOR = '⚓'

let bound = false
let refused = false
let cwd = ''
let home = ''
let state = ''
let config = ''
let bin = ''
let pluginRoot = ''
let generation = ''
let activated = false
let lockPid = ''
// The provider-error latch (counting, cooldown, expiry) is the shared machine.
// What counts as one failure is this host's declared seam: a completed branch
// turn that ended in a provider error or produced no report. Its clock reads
// the host time this module last observed through $.clock.now() - the mockable
// time source in the engine and real time in production - never raw Date.now,
// which the engine's mock clock does not move.
let lastKnownNowMs = Date.now()
const providerLatch = createProviderErrorLatch(PROVIDER_ERROR_LATCH_POLICY, () => lastKnownNowMs)
let wakeCounter = 0
let spawnCount = 0
let sendCount = 0
let branchGeneration = 1
let rotatePending = false
let stepsThisWake = 0
let branchRef = ''
let inFlight: InFlight | null = null
let branchAgentId = ''
const ownAgents = new Set<string>()
const handledSeqs = new Set<string>()
const recentPassed = new Map<string, number>()
let monitorArmed = false
let monitorTaskId = ''
let monitorArmedAt = 0
let armingNow = false
let monitorArms = 0

function branchName(): string {
  return branchGeneration > 1 ? `${BRANCH_NAME}-${branchGeneration}` : BRANCH_NAME
}

function scriptEnv(extra: Record<string, string> = {}): Record<string, string> {
  return {
    FM_HOME: home,
    FM_STATE_OVERRIDE: state,
    FM_CONFIG_OVERRIDE: config,
    FM_WAKE_QUEUE: `${state}/.wake-queue`,
    FM_WAKE_QUEUE_LOCK: `${state}/.wake-queue.lock`,
    ...extra,
  }
}

function appendLine($: any, path: string, line: string, cap: number): Promise<unknown> {
  // One shell append per record, rotated once past the cap so the log cannot grow without bound.
  const script = 'f=$1; cap=$2; if [ -f "$f" ] && [ "$(wc -c < "$f")" -gt "$cap" ]; then mv -f "$f" "$f.1"; fi; cat >> "$f"'
  return $.process.run(['sh', '-c', script, '_', path, String(cap)], { stdin: line, timeoutMs: 3000 })
}

// Append-only event log: the evidence source for every count the live test asserts.
function log($: any, kind: string, data: unknown): void {
  if (!state) return
  const line = JSON.stringify({ t: new Date().toISOString(), kind, data }) + '\n'
  void appendLine($, `${state}/branch-mod-events.jsonl`, line, EVENT_LOG_CAP_BYTES).catch(() => {})
}

function parentDirectory(path: string): string {
  const cut = path.replace(/\/+$/, '').lastIndexOf('/')
  return cut > 0 ? path.slice(0, cut) : '/'
}

// Home and script resolution follow bin/ exactly: FM_HOME, then FM_ROOT_OVERRIDE,
// then the tracked code root three levels above the plugin folder; state and
// config honour their own overrides; scripts always come from the code root.
export async function bind($: any, sessionCwd: string): Promise<void> {
  if (bound) return
  bound = true
  cwd = sessionCwd
  pluginRoot = $.plugin.root
  const codeRoot = parentDirectory(parentDirectory(parentDirectory(pluginRoot)))
  // Literal names only: strict validation lists the variables a module reads.
  const text = (v: unknown) => String(v ?? '')
  let fmHome = ''
  let fmRoot = ''
  let fmState = ''
  let fmConfig = ''
  try {
    fmHome = text(await $.env.get('FM_HOME'))
    fmRoot = text(await $.env.get('FM_ROOT_OVERRIDE'))
    fmState = text(await $.env.get('FM_STATE_OVERRIDE'))
    fmConfig = text(await $.env.get('FM_CONFIG_OVERRIDE'))
  } catch {}
  home = fmHome || fmRoot || codeRoot
  state = fmState || `${home}/state`
  config = fmConfig || `${home}/config`
  bin = `${codeRoot}/bin`
  if (!generation) generation = `cc${Date.now()}`
}
async function ensureBound($: any): Promise<void> {
  if (bound) return
  await bind($, await $.session.cwd())
  log($, 'rebound', { cwd, generation })
}

async function modeOn($: any): Promise<boolean> {
  return $.fs.exists(`${state}/.branch-mod-mode`)
}
async function readConfig($: any, name: string, fallback: string): Promise<string> {
  try {
    return (await $.fs.read(`${config}/${name}`)).trim() || fallback
  } catch {
    return fallback
  }
}
// Queue rows the classifier already passed to main, durable across a module
// reload or a session restart: while such a row is still queued it goes back
// to main unclassified, because its lines are HISTORY to the classifier now.
async function readPassedSeqs($: any): Promise<Set<string>> {
  try {
    const j = JSON.parse(await $.fs.read(`${state}/.branch-mod-passed`))
    return new Set(Array.isArray(j) ? j.map(String) : [])
  } catch {
    return new Set()
  }
}
async function writePassedSeqs($: any, seqs: Set<string>): Promise<void> {
  try {
    await $.fs.write(`${state}/.branch-mod-passed`, JSON.stringify([...seqs]))
  } catch {}
}
async function readLockPid($: any): Promise<string> {
  try {
    const raw = (await $.fs.read(`${state}/.lock`)).split('\n')[0].trim()
    return /^[0-9]+$/.test(raw) ? raw : ''
  } catch {
    return ''
  }
}

// Session counters survive a module reload (/reload-plugins): the file is
// bound to the session lock pid, so a genuinely new session starts at zero.
async function saveCounters($: any): Promise<void> {
  try {
    await $.fs.write(
      `${state}/.branch-mod-counters`,
      JSON.stringify({ lockPid: lockPid || (await readLockPid($)), wakeCounter, spawnCount, sendCount, generation, branchGeneration, branchRef, branchAgentId, monitorTaskId, monitorArmedAt }),
    )
  } catch {}
}
async function restoreCounters($: any): Promise<void> {
  try {
    const j = JSON.parse(await $.fs.read(`${state}/.branch-mod-counters`))
    const pid = await readLockPid($)
    if (j.lockPid && j.lockPid === pid) {
      wakeCounter = j.wakeCounter ?? 0
      spawnCount = j.spawnCount ?? 0
      sendCount = j.sendCount ?? 0
      branchGeneration = j.branchGeneration ?? 1
      if (j.generation) generation = j.generation
      if (j.branchRef) branchRef = j.branchRef
      if (j.branchAgentId) {
        branchAgentId = j.branchAgentId
        ownAgents.add(j.branchAgentId)
      }
      if (j.monitorTaskId) {
        monitorTaskId = j.monitorTaskId
        monitorArmedAt = j.monitorArmedAt ?? Number(await $.clock.now())
        monitorArmed = true
      }
      log($, 'counters.restored', { ...j, reason: 'same session lock pid (module reloaded)' })
    }
  } catch {}
}

async function grant($: any, args: string[], timeoutMs = 5000): Promise<number> {
  const r = await $.process.run(['bash', `${bin}/fm-wake-grant.sh`, ...args], { cwd, env: scriptEnv(), timeoutMs })
  return r.exitCode
}
async function ensureActivated($: any): Promise<boolean> {
  if (activated) return true
  lockPid = await readLockPid($)
  if (!lockPid) return false
  const rc = await grant($, ['activate', lockPid, generation])
  activated = rc === 0
  log($, 'grant.activate', { lockPid, generation, rc })
  return activated
}

// ---- eligibility: the shared fold, vendored (bin/fm-branch-shared-sync.sh) ----

// Cross-scan verdict cache keyed by task id, the shared lib's module-level
// posture: one state directory per runtime, so task ids are stable keys and a
// stale row's fold carries across scans on an unchanged stat version.
const verdictCache: DecisionVerdictCache = new Map()

// The FM_CLASSIFY_* names and defaults of bin/fm-classify-lib.sh. The hooks
// host answers $.env.get name by name (no process global in the module
// sandbox, and a literal name at every call site so the host can list the
// variables a module reads), so the four names are read literally and the
// shared lib's defaults rule fills the rest.
async function foldVocabulary($: any): Promise<FoldVocabulary> {
  const [resolveVerb, heldVerb, reservedPrefixes, pausedVerb] = await Promise.all([
    $.env.get('FM_CLASSIFY_RESOLVE_VERB'),
    $.env.get('FM_CLASSIFY_CAPTAIN_HELD_VERB'),
    $.env.get('FM_CLASSIFY_RESERVED_KEY_PREFIXES'),
    $.env.get('FM_CLASSIFY_PAUSED_VERB'),
  ])
  const byName: Record<string, string | undefined> = {
    FM_CLASSIFY_RESOLVE_VERB: resolveVerb === undefined ? undefined : String(resolveVerb),
    FM_CLASSIFY_CAPTAIN_HELD_VERB: heldVerb === undefined ? undefined : String(heldVerb),
    FM_CLASSIFY_RESERVED_KEY_PREFIXES: reservedPrefixes === undefined ? undefined : String(reservedPrefixes),
    FM_CLASSIFY_PAUSED_VERB: pausedVerb === undefined ? undefined : String(pausedVerb),
  }
  return foldVocabularyFromEnv((name) => byName[name])
}

// The stat version of one state-directory file through the host seam, whose
// stat answers { kind, size, mtimeMs, isLink } with lstat semantics (isLink
// true for a symlink itself, the target's size/mtime when it resolves).
// Returns null for a missing, unreadable, or symlinked path - bash's
// `[ -f ] && [ -r ] && [ ! -L ]` guard, via the shared lib's stat rule.
async function statVersionOf($: any, path: string): Promise<string | null> {
  try {
    const stat = await $.fs.stat(path)
    if (stat.isLink) return null
    return `${stat.size}:${stat.mtimeMs}`
  } catch {
    return null
  }
}

// bin/fm-classify-lib.sh _fm_status_kind through the shared lib's parser: a
// symlinked, missing, or unreadable meta names no kind (unknown).
async function statusKind($: any, task: string): Promise<string> {
  const path = `${state}/${task}.meta`
  let metaText: string | null = null
  try {
    const stat = await $.fs.stat(path)
    if (!stat.isLink) metaText = await $.fs.read(path)
  } catch {
    metaText = null
  }
  return statusKindFromMetaText(metaText)
}

// The eligible-rows scan, delegated to the vendored shared core. The host seam
// is async while the core binds sync lookups, so the reads happen first: the
// queue, every .meta record (one unreadable meta refuses the scan exactly as
// the lib's node:fs binding does), each task's kind, and each project-bearing
// task's log with the stat-read-stat torn check. The sync bindings then answer
// from those pre-reads.
export async function scopeForUnreadWake($: any, heartbeat: boolean): Promise<Scope> {
  const unsafe: Scope = { status: 'unsafe', eligible: false, eligibleSeqs: [], eligibleWakeKey: '', eligibleTasks: [], corrupted: true, needsDecisionTasks: [] }
  let queueText: string
  try {
    queueText = await $.fs.read(`${state}/.wake-queue`)
  } catch {
    return unsafe
  }
  // An empty queue is nothing to claim before any metadata enumeration can
  // fail - the shared core's own ordering.
  if (queueText.split(/\r?\n/).filter((l: string) => l.length > 0).length === 0) {
    return { status: 'empty', eligible: false, eligibleSeqs: [], eligibleWakeKey: '', eligibleTasks: [], corrupted: false, needsDecisionTasks: [] }
  }
  const metas: QueueMeta[] = []
  const kinds = new Map<string, string>()
  try {
    for (const entry of await $.fs.list(state)) {
      if (!entry.name.endsWith('.meta')) continue
      const task = entry.name.slice(0, -5)
      const metaPath = `${state}/${entry.name}`
      const text: string = await $.fs.read(metaPath)
      const fields = text.split('\n')
      metas.push({
        task,
        project: fields.find((l: string) => l.startsWith('project='))?.slice(8) ?? '',
        window: fields.find((l: string) => l.startsWith('window='))?.slice(7) ?? '',
      })
      let kind: string
      try {
        kind = (await $.fs.stat(metaPath)).isLink ? 'unknown' : statusKindFromMetaText(text)
      } catch {
        kind = 'unknown'
      }
      kinds.set(task, kind)
    }
  } catch {
    return unsafe
  }
  // The core resolves which stale rows fold a status log; every task the
  // resolution can name is one with a project, so pre-read those logs and let
  // the core consult the ones it needs.
  const stats = new Map<string, StatusStat>()
  const texts = new Map<string, StatusText>()
  for (const { task, project } of metas) {
    if (!project) continue
    const path = `${state}/${task}.status`
    const version = await statVersionOf($, path)
    if (version === null) {
      stats.set(task, { state: 'refused' })
      texts.set(task, { state: 'refused' })
      continue
    }
    stats.set(task, { state: 'ok', version })
    let text: string
    try {
      text = await $.fs.read(path)
    } catch {
      texts.set(task, { state: 'refused' })
      continue
    }
    const after = await statVersionOf($, path)
    texts.set(task, after === null || after !== version ? { state: 'torn' } : { state: 'ok', text, version: after })
  }
  const libScope = libScopeForUnreadWake({
    queueText,
    metas,
    statStatus: (task) => stats.get(task) ?? { state: 'refused' },
    readStatusText: (task) => texts.get(task) ?? { state: 'refused' },
    readKind: (task) => kinds.get(task) ?? 'unknown',
    env: await foldVocabulary($),
    heartbeat,
    // The mod routes the away collapse before scoping (routeWake's .afk
    // check), so the core's own afk branch stays off here.
    afk: false,
    cache: verdictCache,
  })
  return {
    status: libScope.status,
    eligible: libScope.eligible,
    eligibleSeqs: libScope.eligibleSeqs,
    eligibleWakeKey: libScope.eligibleWakeKey,
    eligibleTasks: libScope.eligibleTasks,
    corrupted: libScope.corrupted,
    needsDecisionTasks: libScope.needsDecisionTasks,
    allSeqs: libScope.allSeqs,
  }
}

// Deterministic note of the status lines appended since the task's last outcome.
async function newStatusLinesNote($: any, tasks: string[]): Promise<string> {
  const parts: string[] = []
  for (const task of tasks) {
    let endpoint = 0
    let lastSeq = ''
    try {
      const idx = (await $.fs.read(`${state}/.${task}.branch-outcome-index`)).split('\t')
      if (idx[0] === 'fm-branch-outcome-index-v1' && /^[0-9]+$/.test(idx[2] ?? '')) {
        endpoint = Number(idx[2])
        lastSeq = idx[1]
      }
    } catch {
      endpoint = 0
    }
    let text = ''
    try {
      text = await $.fs.read(`${state}/${task}.status`)
    } catch {
      text = ''
    }
    const fresh = text
      .slice(endpoint)
      .split('\n')
      .filter((l: string) => l.trim())
      .slice(-12)
    if (!lastSeq) parts.push(`No earlier outcome exists for ${task}: the whole status log is new for this wake.`)
    else parts.push(`Status lines of ${task} appended since your last outcome (seq ${lastSeq}):\n` + (fresh.length ? fresh.map((l: string) => `  ${l}`).join('\n') : '  (none - only a turn-end or pane signal)'))
  }
  return parts.length ? `\n\n${parts.join('\n\n')}` : ''
}

function reasonLines(text: string): string[] {
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => /^(signal:|stale:|check:|heartbeat($|:))/.test(l))
}

async function outcome($: any, args: string[]): Promise<{ ok: boolean; stdout: string; detail: string }> {
  const r = await $.process.run(['bash', `${bin}/fm-branch-outcome.sh`, ...args], { cwd, env: scriptEnv(), timeoutMs: 8000 })
  if (r.exitCode === 0) return { ok: true, stdout: r.stdout.trim(), detail: '' }
  return { ok: false, stdout: '', detail: `fm-branch-outcome.sh exited ${r.exitCode}: ${r.stderr.trim()}` }
}

// A registered tool's answer must be a string or content array (core check).
function textResult(text: string, isError = false) {
  return isError ? { deny: text } : { result: text }
}

// Processing request for main: exactly one main turn per captain outcome.
function processingRequest(seq: number, task: string, summary: string, source: string): string {
  return (
    `This is a supervision processing request delivered automatically by the supervision branch (${source}). It was not typed by the captain. ` +
    `The outcome below is already stored durably; the fleet event is already handled, so do not re-drain, re-run, or acknowledge the wake. ` +
    `Process it now as firstmate: tell the captain the outcome in one sentence. ` +
    `Then call fm_branch_processed with through=${seq} exactly once.\n\n[seq ${seq}] ${task}: ${summary}`
  )
}

export async function serveReport($: any, e: any, agentId: string | undefined) {
  const task = String(e.task ?? '').trim()
  const verdict = String(e.verdict ?? '')
  const summary = String(e.summary ?? '').trim()
  const wake = String(e.wake ?? '').trim()
  const silent = e.silent === true
  const p = inFlight
  log($, 'report.call', { agentId, task, verdict, summary, silent, wakeNo: p?.wakeNo })
  const validated = validateBranchReport({ task, verdict, summary, silent })
  if (!validated.valid) {
    return textResult(validated.message, true)
  }
  // The task-in-scope rule is the shared module's; this host's refusal wording
  // (the corrective re-report instruction, no row list) is a declared seam.
  const scopeVerdict = reportTaskScopeVerdict(p && !p.heartbeat ? { rows: [], tasks: [...p.tasks] } : null, task)
  if (!scopeVerdict.allowed) {
    return textResult(`report not recorded: task must be ${scopeVerdict.tasks.join(' or ')} (this wake's own task), not '${task}'. Call fm_branch_report again with task=${scopeVerdict.tasks[0]} and the same verdict and summary.`)
  }
  if (p && p.reportedSeqs.length > 0 && !p.heartbeat) {
    log($, 'report.duplicate', { agentId, task, verdict, priorSeqs: p.reportedSeqs })
    return textResult(`already recorded seq ${p.reportedSeqs[p.reportedSeqs.length - 1]} for this wake; one report per wake is enough. Do not report again: run the exact --ack-through command the drain printed and end your turn with the word done.`)
  }
  const args = reportAppendArgv(validated, wake || null, p?.wakeKey && /^[0-9:,]+$/.test(p.wakeKey) ? ['--wake-key', p.wakeKey] : undefined)
  const appended = await runSettlementStep((argv) => outcome($, argv), args)
  if (!appended.ok) return textResult(appendFailureMessage(appended.detail), true)
  const seq = Number(appended.stdout)
  if (p) p.reportedSeqs.push(seq)
  const marked = await runSettlementStep((argv) => outcome($, argv), markReadArgv(seq))
  if (!marked.ok) return textResult(`recorded seq ${seq}, but cursor advancement failed: ${marked.detail}`, true)
  if (verdict === 'routine') {
    if (!silent) $.ui.log(`${BOAT} ${task}: ${summary}`)
    log($, 'deliver.routine', { seq, task, summary, silent, wakeNo: p?.wakeNo })
  } else {
    $.ui.log(`${ANCHOR} [seq ${seq}] ${task}: ${summary}`)
    void $.prompt.submit({ text: processingRequest(seq, task, summary, 'branch verdict captain') }).catch((err: unknown) => log($, 'deliver.captain.error', { seq, error: String(err) }))
    log($, 'deliver.captain', { seq, task, summary, wakeNo: p?.wakeNo })
  }
  return textResult(reportSuccessMessage(seq, validated.verdict))
}

export async function serveProcessed($: any, e: any) {
  const through = Number(e.through)
  if (!validateThroughValue(through)) return textResult('through must be a positive integer', true)
  const r = await runSettlementStep((argv) => outcome($, argv), markProcessedArgv(through))
  log($, 'processed.call', { through, ok: r.ok, detail: r.ok ? '' : r.detail })
  if (!r.ok) return textResult(`processed marker not advanced: ${r.detail}`, true)
  return textResult(`captain outcomes through seq ${through} marked processed`)
}

// Behavior-neutral test seams (same precedent as scopeForUnreadWake): the
// portable equivalence test drives the real handlers and plants the in-flight
// wake record the scoping rule reads (tests/fm-branch-report-sequence.test.sh).
export function __fmSetInFlight(p: InFlight | null): void {
  inFlight = p
}

// Rewake banner in the Stop hook's own shape, so a wake main must take reaches
// it exactly as the hook would have delivered it.
function rewakeBanner(reason: string): string {
  return (
    `<task-notification>\n<summary>Stop hook feedback</summary>\n</task-notification>\n<system-reminder>\n` +
    `Stop hook blocking error from command "Stop": firstmate watcher wake - one supervision event needs a handling turn now.\n${reason}\n` +
    `Run bin/fm-wake-drain.sh first, handle the wake, then run its exact WAKE_ACK_REQUIRED --ack-through command. Until that post-handling acknowledgement, interruption leaves the wake durable for idempotent re-handling. This Stop hook owns watcher continuity: when the handling turn ends, the next needed cycle arms automatically - do NOT run bin/fm-watch-arm.sh after an ordinary wake.\n</system-reminder>`
  )
}

// ---- classifier ahead of the branch ----
// The classifier core - the evidence byte-range parse and failure text of
// bin/fm-wake-evidence.sh, the prompt construction, the answer
// interpretation rule, and the durable record shape - is the shared module
// (vendored into ../lib by bin/fm-branch-shared-sync.sh); this host binds its
// seams. Exported for the portable tests (same precedent as serveReport).
function classifierDeps($: any) {
  return {
    paths: { bin },
    runScript: (argv: string[], opts: { timeoutMs: number }) => $.process.run(argv, { cwd, env: scriptEnv(), timeoutMs: opts.timeoutMs }),
    readSystemPrompt: () => $.fs.read(`${pluginRoot}/classifier-system.txt`),
    // The explicit classifier-model line wins; this host's default is
    // haiku, also the one-shot fallback when a configured name does not
    // resolve. The shared module resolves configured-wins-then-default
    // before any completion call.
    readConfiguredModel: async () => (await readConfig($, 'classifier-model', '')) || null,
    readDefaultModel: async () => 'haiku',
    complete: async (req: { model: string; system: string; prompt: string; maxTokens: number }) => String(await $.model.complete(req)),
    clock: { now: () => Date.now(), iso: () => new Date().toISOString() },
  }
}

export async function classify($: any, reason: string, tasks: string[], seqs: string[]): Promise<ClassifierResult> {
  const { result, recordLine } = await classifyWake(classifierDeps($), { wake: reason, tasks, seqs })
  // The durable classification log: one record per call, scored later by
  // bin/fm-branch-classifier-score.sh against the status lines main had to act on.
  try {
    await appendLine($, `${state}/branch-mod-classifications.jsonl`, recordLine, EVENT_LOG_CAP_BYTES)
  } catch (error) {
    log($, 'classifier.log.error', { error: String(error) })
  }
  return result
}

// ---- shadow advisory trial (config/classifier-shadow) ----
// When config/classifier-shadow names `jev`, every granted wake also issues a
// detached, bounded question bundle to the TypeSafe System One model
// (jev-latest) through bin/fm-branch-shadow-jev.sh, over the state this mod
// just classified with. The trial must never delay or alter the wake: it runs
// as a void promise beside delivery, each call has its own timeout, and one
// record per ablation variant is appended to state/branch-mod-shadow.jsonl
// for bin/fm-branch-shadow-score.sh. Any failure appends an `unavailable`
// record and moves on. The API key lives only inside the bash helper;
// TypeScript never reads it.
// The trial core - the evidence parsers, the question bundle, the facts
// object, the variant set, the answer parsing, and the record shape - is the
// shared module (vendored into ../lib by bin/fm-branch-shared-sync.sh); this
// host binds its seams. Exported for the portable tests (same precedent as
// serveReport).
function shadowDeps($: any) {
  return {
    paths: { bin, state },
    readFile: (path: string) => $.fs.read(path),
    hasOpenCall: async (task: string) => {
      try {
        const lines = (await $.fs.read(`${state}/${task}.status`)).split(/\r?\n/)
        return hasOpenNeedsDecision(lines, await statusKind($, task), await foldVocabulary($))
      } catch {
        return false
      }
    },
    runScript: (argv: string[], opts: { timeoutMs: number; stdin?: string }) =>
      $.process.run(argv, { cwd, env: scriptEnv(), timeoutMs: opts.timeoutMs, ...(opts.stdin !== undefined ? { stdin: opts.stdin } : {}) }),
    readConfig: (name: string, fallback: string) => readConfig($, name, fallback),
    appendShadowRecord: async (line: string) => {
      await appendLine($, `${state}/branch-mod-shadow.jsonl`, line, EVENT_LOG_CAP_BYTES)
    },
    onShadowError: (kind: 'shadow.error' | 'shadow.log.error', error: unknown) => log($, kind, { error: String(error) }),
    clock: { now: () => Date.now(), iso: () => new Date().toISOString() },
  }
}

export async function runShadowAdvisory($: any, a: { wake: string; seqs: string[]; wakeKey: string; tasks: string[]; evidence: ClassifierEvidence[]; wakeNo: number }): Promise<void> {
  return libRunShadowAdvisory(shadowDeps($), a)
}

// ---- delivery to the one persistent branch agent ----
async function resolveBranchAgentId($: any): Promise<string> {
  try {
    const list = await $.agent.list()
    const name = branchName()
    const named = (list as any[]).filter((a) => a.name === name)
    log($, 'agent.list', { count: (list as any[]).length, named })
    const live = named.at(-1)
    return live?.id ?? ''
  } catch (error) {
    log($, 'agent.list.error', { error: String(error) })
    return ''
  }
}

function toolText(r: any): string {
  return String(r?.text ?? r?.result ?? '')
}

// One SendMessage to the named branch. The harness pins a name to the agent it
// first reached in this conversation; when the name later resolves elsewhere
// (module reload, second spawn) the reply is {"success":false,"message":"...
// re-send with its ref: {"to": "fm-branch [3a11a1]"}"} and nothing is sent, so
// the pinned ref is learned from that text and the send retried once.
async function sendToBranch($: any, prompt: string): Promise<{ ok: boolean; id: string; detail: string; noAgent: boolean }> {
  const name = branchName()
  const sessionId = await sessionTranscriptId($)
  for (let attempt = 0; attempt < 2; attempt++) {
    const to = branchRef ? `${name} [${branchRef}]` : name
    let r: any
    try {
      r = await $.tool.call({ tool: 'SendMessage', to, summary: 'fm-branch-mod wake', message: prompt })
    } catch (error) {
      r = { deny: String(error) }
    }
    sendCount += 1
    const text = toolText(r)
    log($, 'agent.send', { to, agentId: branchAgentId, sessionId, sendCount, attempt, text: text.slice(0, 400), deny: r?.deny, isError: r?.isError })
    if (r?.deny || r?.isError) {
      const failure = String(r?.deny ?? text)
      return { ok: false, id: '', detail: failure.slice(0, 300), noAgent: /no agent|not found|unknown agent|could not be resumed|no transcript found/i.test(failure) }
    }
    let j: any = {}
    try {
      j = JSON.parse(text)
    } catch {}
    if (j.success === false) {
      const hint = text.match(new RegExp(`${name} \\[([0-9a-f]+)\\]`))
      if (hint && hint[1] !== branchRef) {
        branchRef = hint[1]
        continue
      }
      return { ok: false, id: '', detail: String(j.message ?? text).slice(0, 300), noAgent: /no agent|not found|unknown agent|does not resolve|could not be resumed|no transcript found/i.test(text) }
    }
    if (j.pin?.ref) branchRef = j.pin.ref
    return { ok: true, id: String(j.resumedAgentId ?? j.pin?.id ?? ''), detail: text.slice(0, 200), noAgent: false }
  }
  return { ok: false, id: '', detail: 'ref changed twice', noAgent: false }
}

async function spawnBranch($: any, prompt: string, model: string): Promise<{ ok: boolean; detail: string }> {
  let spawned: any
  try {
    spawned = await $.agent.spawn({ prompt, description: 'firstmate supervision branch (persistent)', subagentType: `${PLUGIN}:${BRANCH_NAME}`, model, background: true, name: branchName() })
  } catch (error) {
    spawned = { deny: String(error) }
  }
  log($, 'agent.spawn', { model, name: branchName(), branchGeneration, result: spawned })
  if (!spawned?.agentId) return { ok: false, detail: String(spawned?.deny ?? 'no agentId') }
  spawnCount += 1
  branchAgentId = spawned.agentId
  ownAgents.add(branchAgentId)
  branchRef = ''
  await saveCounters($)
  return { ok: true, detail: branchAgentId }
}

// One rotation per delivery: a fresh agent under the next generation name
// takes over, and the old one simply never receives another message.
async function rotateToFreshAgent($: any, prompt: string, model: string, why: string, sendDetail?: string): Promise<{ ok: boolean; via: 'spawn'; detail: string }> {
  branchGeneration += 1
  branchAgentId = ''
  branchRef = ''
  const s = await spawnBranch($, prompt, model)
  log($, 'agent.rotated', { why, branchGeneration, name: branchName(), ok: s.ok, detail: s.detail, sendDetail })
  await saveCounters($)
  return { ok: s.ok, via: 'spawn', detail: s.detail }
}

async function deliverToBranch($: any, prompt: string): Promise<{ ok: boolean; via: 'spawn' | 'send'; detail: string }> {
  const model = await readConfig($, 'supervision-branch-model', 'sonnet')
  if (rotatePending) {
    // The previous agent's context passed the bound.
    rotatePending = false
    return rotateToFreshAgent($, prompt, model, 'context bound')
  }
  if (!branchAgentId) {
    // A module reload (/reload-plugins, or a hooks file save) resets this state
    // while the named agent lives on in the session. $.agent.list() is scoped to
    // this module instance, so adoption goes through SendMessage itself: a
    // successful resume names the agent's id. A session that never spawned has
    // nothing to adopt and spawns directly, so the first wake costs no refused
    // send.
    if (spawnCount > 0) {
      const s = await sendToBranch($, prompt)
      if (s.ok) {
        log($, 'agent.adopted', { agentId: s.id, ref: branchRef })
        branchAgentId = s.id
        if (s.id) ownAgents.add(s.id)
        await saveCounters($)
        return { ok: true, via: 'send', detail: s.id }
      }
      log($, 'agent.adopt.failed', { detail: s.detail, noAgent: s.noAgent })
    }
    const spawned = await spawnBranch($, prompt, model)
    return { ok: spawned.ok, via: 'spawn', detail: spawned.detail }
  }
  const s = await sendToBranch($, prompt)
  if (!s.ok) {
    // A resumed agent whose transcript was never written (a bridge primary
    // runs with transcript saving off) is unreachable for good: rotate to a
    // fresh agent instead of passing every later wake to main.
    if (!s.noAgent) return { ok: false, via: 'send', detail: s.detail }
    return rotateToFreshAgent($, prompt, model, 'unresumable', s.detail)
  }
  if (s.id && s.id !== branchAgentId) {
    log($, 'agent.id.changed', { from: branchAgentId, to: s.id })
    branchAgentId = s.id
  }
  if (s.id) ownAgents.add(s.id)
  return { ok: true, via: 'send', detail: s.id || branchAgentId }
}

// Route one watcher wake: 'dropped' when the branch took it, 'passed' when main must handle it.
async function routeWake($: any, wakeText: string, source: string): Promise<'dropped' | 'passed'> {
  const reasons = reasonLines(wakeText)
  const reason = reasons.join('\n')
  const now = Number(await $.clock.now())
  lastKnownNowMs = now
  // Dedupe key: the queue rows the wake resolves to, never the reason text,
  // because every wake of one task reads the same `signal: .../<task>.status`.
  let passKey = ''
  const pass = (why: string, extra: Record<string, unknown> = {}) => {
    log($, 'wake.passed', { why, reason: reason || wakeText.slice(0, 300), source, ...extra })
    if (passKey) recentPassed.set(passKey, now)
    // Lines main handles become history for the classifier: advance its offset.
    const tasks = new Set<string>([...((extra.seqsTasks as string[]) ?? []), ...((extra.needsDecisionTasks as string[]) ?? [])])
    for (const t of tasks) void $.process.run(['bash', `${bin}/fm-wake-evidence.sh`, t], { cwd, env: scriptEnv(), timeoutMs: 25000 }).catch(() => {})
    // A captain-class wake main takes directly still needs a covering CAPTAIN
    // row in the outcome store: without it the branch's next wake note lists
    // the line as "appended since your last outcome" and re-escalates what
    // main already handled, and the backstop reads the line as uncovered.
    if (/^(classifier|scope unsafe)/.test(why)) {
      for (const t of tasks) {
        void (async () => {
          const coverSummary = passedToMainSummary(why, String(extra.classifierReason ?? 'open captain decision on this task'))
          const a = await outcome($, classifierPassCoverArgv(t, coverSummary, reason))
          if (!a.ok) return log($, 'pass.cover.error', { task: t, detail: a.detail })
          const seq = Number(a.stdout)
          await outcome($, ['mark-read', '--through', String(seq)])
          const m = await outcome($, ['mark-processed', '--through', String(seq)])
          log($, 'pass.cover', { task: t, seq, why, processed: m.ok, detail: m.detail })
        })().catch((error) => log($, 'pass.cover.error', { task: t, detail: String(error) }))
      }
    }
    return 'passed' as const
  }
  if (!(await modeOn($))) return pass('no state/.branch-mod-mode')
  if (providerLatch.admitWake().decision === 'latched') return pass('latched')
  if (await $.fs.exists(`${state}/.afk`)) return pass('afk')
  if (reasons.length === 0) return pass('no actionable reason line (alarm or failure notice)')
  const heartbeat = reasons.some((r) => /^heartbeat($|:)/.test(r))
  const scope = await scopeForUnreadWake($, heartbeat)
  log($, 'wake.scope', { reason, scope, source })
  const passedSeqs = await readPassedSeqs($)
  if (scope.allSeqs || scope.status === 'empty') {
    const queued = new Set(scope.allSeqs ?? [])
    const gone = [...passedSeqs].filter((s) => !queued.has(s))
    if (gone.length > 0) {
      for (const s of gone) passedSeqs.delete(s)
      await writePassedSeqs($, passedSeqs)
    }
  }
  passKey = `${scope.status}:${(scope.allSeqs ?? scope.eligibleSeqs).join(',')}:${scope.needsDecisionTasks.join(',')}`
  const seenAt = recentPassed.get(passKey)
  if (seenAt !== undefined && now - seenAt < PASSED_DEDUPE_MS) {
    log($, 'wake.passed.deduped', { passKey, source, ageMs: now - seenAt })
    return 'dropped'
  }
  // An empty queue under a signal/stale/heartbeat reason means the other
  // continuity path (Stop hook vs Monitor) already routed this close: nothing
  // for main to drain, so drop it. A `check:` reason (recovery marker,
  // registered poll) still needs main's acknowledgement and is passed.
  if (scope.status === 'empty' && !reasons.some((r) => /^check:/.test(r))) {
    log($, 'wake.dropped.empty', { reason, source })
    return 'dropped'
  }
  if (scope.status === 'empty' || scope.corrupted || scope.eligibleSeqs.length === 0) return pass(`scope ${scope.status}`, { needsDecisionTasks: scope.needsDecisionTasks, seqsTasks: scope.eligibleTasks })
  // Dedupe: the Stop-hook arm and the monitor can both surface one wake, and a
  // wake already in the branch's hands must not be granted twice.
  if (scope.eligibleSeqs.every((s) => handledSeqs.has(s))) {
    log($, 'wake.deduped', { seqs: scope.eligibleSeqs, source })
    return 'dropped'
  }
  if (inFlight && Date.now() - inFlight.startedAt > INFLIGHT_STALE_MS) {
    // A delivery that never settled (send refused, agent gone): free the grant
    // and route afresh rather than queueing every later wake behind it.
    log($, 'inflight.stale', { seqs: inFlight.seqs, wakeNo: inFlight.wakeNo, ageMs: Date.now() - inFlight.startedAt })
    inFlight = null
    for (const s of scope.eligibleSeqs) handledSeqs.delete(s)
    await grant($, ['release', generation]).catch(() => {})
  }
  if (inFlight) {
    // The grant file holds one row set at a time; the branch's settlement
    // re-scopes the queue and routes what is still there.
    log($, 'wake.queued', { seqs: scope.eligibleSeqs, source, inFlightSeqs: inFlight.seqs })
    return 'dropped'
  }
  const unacknowledged = scope.eligibleSeqs.filter((s) => passedSeqs.has(s))
  if (unacknowledged.length > 0) {
    for (const s of scope.eligibleSeqs) passedSeqs.add(s)
    await writePassedSeqs($, passedSeqs)
    return pass('classifier skipped: rows already passed to main, unacknowledged', { classifierReason: `row ${unacknowledged.join(', ')} of this wake was already passed to main and is not yet acknowledged`, seqs: scope.eligibleSeqs, seqsTasks: scope.eligibleTasks })
  }
  // Classifier ahead of the branch: only a confident routine verdict is
  // granted; captain or uncertain goes to main untouched.
  const c = await classify($, reason, scope.eligibleTasks, scope.eligibleSeqs)
  // The event log keeps the record shape but never the evidence texts; the
  // shadow advisory receives them in memory only.
  log($, 'classifier', { seqs: scope.eligibleSeqs, tasks: scope.eligibleTasks, verdict: c.verdict, reason: c.reason, ms: c.ms, promptChars: c.promptChars, answer: c.answer, model: c.model, estTokens: Math.ceil(c.promptChars / 4) })
  if (c.verdict !== 'routine') {
    for (const s of scope.eligibleSeqs) passedSeqs.add(s)
    await writePassedSeqs($, passedSeqs)
    return pass(`classifier ${c.verdict}`, { classifierReason: c.reason, seqs: scope.eligibleSeqs, seqsTasks: scope.eligibleTasks })
  }
  if (!(await ensureActivated($))) return pass('no lock pid / activation failed')
  const rc = await grant($, ['publish', generation, ...scope.eligibleSeqs])
  log($, 'grant.publish', { seqs: scope.eligibleSeqs, rc })
  if (rc !== 0) return pass(rc === 3 ? 'main-owned' : `publish rc ${rc}`)
  wakeCounter += 1
  await saveCounters($)
  const freshAgent = rotatePending || !branchAgentId
  const scopeNote = heartbeat
    ? ''
    : `\n\nThis wake's rows resolve to task ${scope.eligibleTasks.join(', ')} (records: ${state}/${scope.eligibleTasks[0]}.meta and ${state}/${scope.eligibleTasks[0]}.status). Report with task=${scope.eligibleTasks[0]}, never fleet.` +
      (await newStatusLinesNote($, scope.eligibleTasks))
  const prompt = `FIRSTMATE SUPERVISION WAKE: ${reason}\n\n(wake ${wakeCounter} of this session)\nHandle this per your operating procedure and finish with fm_branch_report.` + scopeNote
  inFlight = {
    seqs: scope.eligibleSeqs,
    wakeKey: scope.eligibleWakeKey,
    tasks: new Set(scope.eligibleTasks),
    heartbeat,
    wakeText,
    reason,
    reportedSeqs: [],
    startedAt: Date.now(),
    granted: true,
    wakeNo: wakeCounter,
    via: freshAgent ? 'spawn' : 'send',
  }
  stepsThisWake = 0
  // Shadow advisory trial: detached and bounded, never delaying or altering
  // the delivery below. Any failure is recorded as unavailable by the trial
  // itself; nothing here may change the wake.
  if (c.evidence.length > 0) void runShadowAdvisory($, { wake: reason, seqs: scope.eligibleSeqs, wakeKey: scope.eligibleWakeKey, tasks: scope.eligibleTasks, evidence: c.evidence, wakeNo: wakeCounter })
  const d = await deliverToBranch($, prompt)
  log($, 'wake.delivered', { wakeNo: wakeCounter, seqs: scope.eligibleSeqs, ...d, spawnCount, sendCount, source })
  if (!d.ok) {
    inFlight = null
    await grant($, ['release', generation]).catch(() => {})
    return pass(`delivery failed via ${d.via}: ${d.detail}`)
  }
  for (const s of scope.eligibleSeqs) handledSeqs.add(s)
  log($, 'wake.dropped', { wakeNo: wakeCounter, source })
  return 'dropped'
}

// ---- continuity: one Monitor task per session, re-armed on expiry ----
async function armMonitor($: any, why: string): Promise<void> {
  if (armingNow) return
  // Claim before the first await: the rotate event and the source-ended notice
  // of one monitor arrive within milliseconds and would otherwise arm two loops.
  armingNow = true
  const now = Number(await $.clock.now())
  if (monitorArmed) {
    const ageMs = now - monitorArmedAt
    if (ageMs < MONITOR_CLAIM_STALE_MS) {
      armingNow = false
      return
    }
    log($, 'monitor.stale.claim', { why, taskId: monitorTaskId, ageMs })
  }
  if (!(await modeOn($))) {
    armingNow = false
    return
  }
  monitorArmed = true
  monitorArmedAt = now
  monitorArms += 1
  // Each watcher close prints its reason lines (one event); the loop re-arms
  // the watcher itself so no per-wake background task is ever started.
  // Re-arm only once the previous wake's rows are acknowledged (queue empty)
  // and any recovery marker (state/.watcher-down) is absent or acked: arming
  // over either makes the watcher announce `check: rearm-resurface` with a
  // fresh recovery generation every cycle, which the Stop-hook model never does.
  // The loop must leave before the Monitor's own kill: the kill takes the whole
  // process group with it, watcher included, and one quiet watcher cycle can
  // outpark any fixed deadline. So every fm-watch-arm.sh call carries the
  // remaining budget as --follow-budget: the arm returns at the deadline
  // leaving the verified healthy watcher running, the loop reaches its rotate
  // check and exits cleanly, and the next Monitor's first arm attaches to the
  // same watcher - no downtime episode, no empty rearm-resurface wake.
  const rotateSecs = Math.floor(MONITOR_TIMEOUT_MS / 1000) - 180
  const command =
    `cd ${JSON.stringify(cwd)} && export FM_HOME=${JSON.stringify(home)} FM_STATE_OVERRIDE=${JSON.stringify(state)} FM_CONFIG_OVERRIDE=${JSON.stringify(config)}; ` +
    `A=${JSON.stringify(bin + '/fm-watch-arm.sh')}; Q=${JSON.stringify(state + '/.wake-queue')}; D=${JSON.stringify(state + '/.watcher-down')}; T0=$(date +%s); DL=$(( T0 + ${rotateSecs} )); ` +
    `while :; do R=$(( DL - $(date +%s) )); [ "$R" -ge 60 ] || { printf 'rotate: loop exiting ahead of the monitor timeout\\n'; exit 0; }; ` +
    `out=$("$A" --follow-budget $(( R - 30 )) 2>&1); printf '%s\\n' "$out" | grep -E '^(signal:|stale:|check:|heartbeat)' || printf 'quiet: %s\\n' "$(printf '%s' "$out" | tail -n 1 | cut -c1-160)"; ` +
    `w=0; while { [ -s "$Q" ] || { [ -e "$D" ] && ! grep -q '^acked:' "$D"; }; } && [ $w -lt 300 ] && [ "$(date +%s)" -lt "$DL" ]; do sleep 2; w=$((w+2)); done; [ $w -lt 300 ] || printf 'forced-rearm: queue or recovery marker still pending after %ss\\n' "$w"; ` +
    `[ "$(date +%s)" -lt "$DL" ] || { printf 'rotate: loop exiting ahead of the monitor timeout\\n'; exit 0; }; sleep 2; done`
  try {
    const r = await $.tool.call({ tool: 'Monitor', command, description: MONITOR_DESCRIPTION, timeout_ms: MONITOR_TIMEOUT_MS })
    const text = toolText(r)
    monitorTaskId = text.match(/Monitor started \(task ([a-z0-9]+)/)?.[1] ?? ''
    log($, 'monitor.armed', { why, monitorArms, taskId: monitorTaskId, text: text.slice(0, 300), deny: r?.deny })
    if (r?.deny) monitorArmed = false
    await saveCounters($)
  } catch (error) {
    monitorArmed = false
    log($, 'monitor.error', { why, error: String(error) })
  } finally {
    armingNow = false
  }
}

// Turn a monitor event notification into the Stop hook's banner shape, or
// null when the text is not one of ours / carries no actionable reason.
function monitorEventBanner($: any, text: string): { banner: string | null; ours: boolean; expired: boolean } {
  const ours = text.includes(MONITOR_DESCRIPTION)
  if (!ours) return { banner: null, ours: false, expired: false }
  // Events arrive as <event>line</event> blocks; the expiry notice arrives as an
  // event too: `<event>[Monitor expired after 30m with N events delivered. ...]</event>`.
  const all = [...text.matchAll(/<event>([\s\S]*?)<\/event>/g)].map((m) => m[1])
  const events = all.filter((t) => !/^\s*(\[Monitor |rotate:)/.test(t))
  const expired = all.length === 0 || events.length < all.length
  const reasons = reasonLines(events.join('\n'))
  log($, 'monitor.event', { reasons, expired, text: text.slice(0, 500) })
  return { banner: reasons.length ? rewakeBanner(reasons.join('\n')) : null, ours: true, expired }
}

// ---- deterministic main-side backstop after a routine branch outcome ----
async function backstopCheck($: any, tasks: Set<string>, wakeNo: number): Promise<void> {
  for (const task of tasks) {
    const r = await $.process.run(['bash', `${bin}/fm-wake-evidence.sh`, '--routine-covered', task], { cwd, env: scriptEnv(), timeoutMs: 15000 })
    const lines = String(r.stdout)
      .split('\n')
      .filter((l: string) => l.trim())
    log($, 'backstop.check', { task, wakeNo, rc: r.exitCode, lines, stderr: String(r.stderr).slice(0, 200) })
    if (lines.length === 0) continue
    const text =
      `Supervision backstop (deterministic, delivered automatically by fm-branch-mod, not typed by the captain): the supervision branch marked a wake of task ${task} routine, but the status log carries ${lines.length} captain-facing line(s) it covered:\n` +
      lines.map((l: string) => `  ${l.split('\t').slice(1).join('\t')}`).join('\n') +
      `\n\nRun bin/fm-wake-drain.sh (its STATUS OUTCOME BACKSTOP section names the same line), tell the captain the outcome in one sentence, then run the exact --ack-through command it printed.`
    try {
      await $.prompt.submit({ text })
      log($, 'backstop.delivered', { task, wakeNo, lines })
    } catch (error) {
      log($, 'backstop.error', { task, wakeNo, error: String(error) })
    }
  }
}

function bashRewrite(e: any, holder: string): any {
  const command = String(e.command)
  return { ...e, command: `export FM_SUPERVISION_ACTOR=branch FM_LEASE_HOLDER_PID=${holder || '$$'} FM_HOME=${JSON.stringify(home)} FM_STATE_OVERRIDE=${JSON.stringify(state)} FM_CONFIG_OVERRIDE=${JSON.stringify(config)}\n(\n${command}\n)` }
}

// The version pin: the module is measured against one Claude Code release and
// refuses every other one, so a silent engine change cannot reroute wakes.
// The binary actually hosting this session decides: the launcher execs the
// pinned release by absolute path to survive the installer symlink moving, so
// PATH can name a different release than the one running here. The probe runs
// the host binary's own `--version` through /proc (Linux only); the PATH call
// stays as the fallback, and a probe answer without a version shape is treated
// as unavailable so a misresolved executable can never cause a false refusal.
// The answer names which source decided and the probe's raw output, so a split
// between the two is one log line.
type PinCheck = { version: string; source: 'running binary' | 'PATH claude'; probe: string }

async function checkPin($: any): Promise<PinCheck> {
  let probe = ''
  try {
    const r = await $.process.run(['sh', '-c', 'exec "$(readlink /proc/$PPID/exe)" --version'], { timeoutMs: 10000 })
    probe = String(r.stdout ?? '').trim().slice(0, 200)
    const version = probe.split(/\s+/)[0] ?? ''
    if (/^\d+\.\d+\.\d+/.test(version)) return { version, source: 'running binary', probe }
  } catch (error) {
    probe = `unreadable (${String(error)})`
  }
  try {
    const r = await $.process.run(['claude', '--version'], { timeoutMs: 10000 })
    return { version: String(r.stdout ?? '').trim().split(/\s+/)[0] ?? '', source: 'PATH claude', probe }
  } catch (error) {
    return { version: `unreadable (${String(error)})`, source: 'PATH claude', probe }
  }
}

// Row 3 of the branch-reuse RCA (2026-09-19): the next transcript regression
// must be one log line instead of a scout. Persistence is off when the session
// inherited the CLAUDE_CODE_CHILD_SESSION marker (a Herdr server started inside
// a Claude session hands it to every pane) and back on when
// CLAUDE_CODE_FORCE_SESSION_PERSISTENCE is set; the launch-option and test-env
// disable causes are not visible to a hook, so their absence reads as default.
async function transcriptPersistence($: any): Promise<{ on: boolean; cause: string }> {
  // Literal names only: strict validation lists the variables a module reads.
  let force = ''
  let marker = ''
  try {
    force = String(await $.env.get('CLAUDE_CODE_FORCE_SESSION_PERSISTENCE') ?? '')
  } catch {}
  try {
    marker = String(await $.env.get('CLAUDE_CODE_CHILD_SESSION') ?? '')
  } catch {}
  if (force) return { on: true, cause: 'CLAUDE_CODE_FORCE_SESSION_PERSISTENCE' }
  if (marker) return { on: false, cause: 'inherited CLAUDE_CODE_CHILD_SESSION marker' }
  return { on: true, cause: 'default' }
}

// The primary session's transcript id: resume reads the branch agent's
// transcript under it (<session>/subagents/agent-<id>.jsonl), so a send log
// naming both is the resume target the next regression needs; where the engine
// does not expose it the reason is logged in its place.
async function sessionTranscriptId($: any): Promise<string> {
  try {
    return String(await $.session.id() ?? '')
  } catch (error) {
    return `unavailable (${String(error)})`
  }
}

export function register(on: On) {
  on('session.start', async ($, e, next) => {
    await bind($, e.cwd)
    const { version, source: pinSource, probe } = await checkPin($)
    if (version !== CLAUDE_CODE_PIN) {
      refused = true
      $.ui.log(`${PLUGIN}: refusing to load on Claude Code ${version || 'unknown'} (${pinSource}); built for ${CLAUDE_CODE_PIN}`)
      log($, 'pin.refused', { version, pin: CLAUDE_CODE_PIN, pinSource, probe })
      return next(e)
    }
    const persistence = await transcriptPersistence($)
    refused = false
    generation = `cc${Date.now()}`
    activated = false
    inFlight = null
    branchAgentId = ''
    spawnCount = 0
    sendCount = 0
    wakeCounter = 0
    branchGeneration = 1
    rotatePending = false
    monitorArmed = false
    handledSeqs.clear()
    await restoreCounters($)
    // Continuity must not wait for a captain prompt: a module reload followed
    // by silence left no Monitor at all, so a Stop-hook-sourced wake the branch
    // absorbed never re-armed one and supervision went dark. Arm at session
    // start when the mode file is present and this session holds the lock - the
    // same evidence restoreCounters reads, never a new lock mechanism.
    // armMonitor's own claim keeps a restored live monitor from double-arming.
    const mode = await modeOn($)
    const lockPid = await readLockPid($)
    if (mode && lockPid) void armMonitor($, 'session start')
    else log($, 'monitor.skipped', { why: 'session start', mode, lockPid })
    try {
      await $.tool.register({
        name: 'fm_branch_report',
        description:
          'Record the outcome of one handled fleet event: writes it durably to the outcome store, then merges it into the captain-facing main conversation. verdict captain opens one processing turn on main; routine notes render without a main turn. Call exactly once per handled event.',
        inputSchema: {
          type: 'object',
          properties: {
            task: { type: 'string', description: "The task id the event belongs to (or 'fleet' for fleet-wide events)" },
            verdict: { type: 'string', enum: ['routine', 'captain'], description: 'Use captain or routine exactly as the "Verdict: routine or captain" section of your system prompt decides.' },
            summary: { type: 'string', description: 'One or two sentences in captain outcome language; include the full https:// PR URL when a PR is involved' },
            wake: { type: 'string', description: 'The wake reason line this outcome answers' },
            silent: { type: 'boolean', description: 'True only when a fleet-wide heartbeat review found literally nothing worth reporting' },
          },
          required: ['task', 'verdict', 'summary'],
        },
      })
      await $.tool.register({
        name: 'fm_branch_processed',
        description: 'Main only: acknowledge that every supervision-branch captain outcome up to and including sequence `through` has been processed. Closes the processing request.',
        inputSchema: { type: 'object', properties: { through: { type: 'number' } }, required: ['through'] },
      })
    } catch (error) {
      log($, 'tool.register.error', { error: String(error) })
    }
    const enabled = await modeOn($)
    $.ui.log(`${PLUGIN}: loaded (${enabled ? 'enabled' : 'inert: no state/.branch-mod-mode'}, home ${home}, Claude Code ${version})`)
    log($, 'session.start', { cwd, home, state, enabled, generation, version, pinSource, probe, persistenceOn: persistence.on, persistenceCause: persistence.cause })
    return next(e)
  }).catch(($, e, next) => next(e))

  on('turn.start', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    log($, 'turn.start', { turnId: e.turnId, text: e.text.slice(0, 300) })
    return next(e)
  })

  on('prompt.submit', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const kind = e.origin?.kind
    if (kind === 'peer') {
      const m = e.text.match(/<agent-message from="([^"]+)"/)
      const from = m?.[1] ?? ''
      if (from.startsWith(BRANCH_NAME) || ownAgents.has(from) || /fm-branch/.test(e.text.slice(0, 200))) {
        log($, 'handback.dropped', { from, text: e.text.slice(0, 300) })
        return { drop: `${PLUGIN}: branch hand-back suppressed` }
      }
      log($, 'prompt.submit.peer', { origin: e.origin, text: e.text.slice(0, 300) })
      return next(e)
    }
    if (kind !== 'task-notification') {
      log($, 'prompt.submit', { origin: e.origin, text: e.text.slice(0, 200) })
      // First captain prompt of the session: arm continuity from a hook frame.
      if (await modeOn($)) void armMonitor($, 'first prompt')
      return next(e)
    }
    const mon = monitorEventBanner($, e.text)
    if (mon.ours) {
      if (mon.expired) {
        // Only the live monitor's own end re-arms: an older monitor's expiry
        // (after a reload reset this state) must not start a second loop.
        const tid = e.text.match(/<task-id>([a-z0-9]+)<\/task-id>/)?.[1] ?? ''
        if ((!monitorTaskId || tid === monitorTaskId) && !armingNow) {
          monitorArmed = false
          void armMonitor($, 'monitor expired')
        } else {
          log($, 'monitor.stale.expiry', { tid, live: monitorTaskId })
        }
      }
      if (!mon.banner) return { drop: `${PLUGIN}: monitor notice without a wake` }
      const verdict = await routeWake($, mon.banner, 'monitor')
      if (verdict === 'dropped') return { drop: `${PLUGIN}: routed to supervision branch` }
      return next({ ...e, text: mon.banner })
    }
    // A completed background agent's own notification (ours) must not open a main turn.
    if (branchAgentId && (e.text.includes(branchAgentId) || /fm-branch\b/.test(e.text)) && !/Stop hook feedback/.test(e.text)) {
      log($, 'agent.notification.dropped', { text: e.text.slice(0, 300) })
      return { drop: `${PLUGIN}: branch agent notification suppressed` }
    }
    const isWake = /<summary>Stop hook feedback<\/summary>/.test(e.text) && /firstmate watcher wake/.test(e.text)
    log($, 'prompt.submit', { origin: e.origin, isWake, text: e.text.slice(0, 600) })
    if (!isWake) return next(e)
    // A wake main's own Stop hook produced must always leave one live cycle
    // behind. If the armed claim is false with no expiry notice in hand (a
    // failed arm, a lost notice), arm here so the next watcher close still
    // surfaces; armMonitor's armed/arming claim is the double-arm guard.
    void armMonitor($, 'stop-hook wake without monitor')
    const verdict = await routeWake($, e.text, 'stop-hook')
    if (verdict === 'dropped') return { drop: `${PLUGIN}: routed to supervision branch` }
    return next(e)
  }).catch(($, e, next) => {
    log($, 'prompt.submit.catch', { text: e.text.slice(0, 200) })
    return next(e)
  })

  // ---- (c) Bash actor rewrite and tool denial for the branch ----
  on('tool.call', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const agentId = (e as { agentId?: string }).agentId
    if (agentId && ownAgents.has(agentId)) {
      if (e.tool === 'Bash') {
        const holder = lockPid || (await readLockPid($))
        log($, 'tool.call.bash', { agentId, wakeNo: inFlight?.wakeNo, command: String((e as any).command).slice(0, 300) })
        return next(bashRewrite(e, holder))
      }
      if (e.tool !== REPORT_TOOL) {
        log($, 'tool.call.denied', { agentId, tool: e.tool })
        return { deny: `${PLUGIN}: the supervision branch may only use Bash and fm_branch_report` }
      }
    } else if (agentId && e.tool === REPORT_TOOL) {
      // Only the branch has this tool: an unknown caller is the branch under a new id.
      log($, 'agent.id.adopted', { agentId, via: 'report tool' })
      ownAgents.add(agentId)
      branchAgentId = agentId
    } else if (agentId && e.tool === 'Bash' && !ownAgents.has(agentId) && branchAgentId) {
      // A Bash call from an unknown subagent while our branch is the only
      // subagent we ever spawn is the branch under a new id (SendMessage resume).
      const id = await resolveBranchAgentId($)
      log($, 'tool.call.unknown-agent', { agentId, resolved: id })
      if (id === agentId) {
        ownAgents.add(agentId)
        branchAgentId = agentId
        const holder = lockPid || (await readLockPid($))
        return next(bashRewrite(e, holder))
      }
    }
    if (e.tool === REPORT_TOOL) return serveReport($, e as any, agentId)
    if (e.tool === PROCESSED_TOOL) return serveProcessed($, e as any)
    return next(e)
  }).catch(($, e, next) => next(e))

  // ---- (f) effort rewrite for the branch's own agent ids ----
  on('turn.step', async function* ($, e, next) {
    if (refused) return yield* next(e)
    const agentId = (e as { agentId?: string }).agentId
    if (agentId && ownAgents.has(agentId)) {
      stepsThisWake += 1
      log($, 'turn.step', { agentId, wakeNo: inFlight?.wakeNo, model: e.model, index: e.index, effort: e.effort, messageCount: e.messageCount })
      return yield* next({ ...e, effort: 'low' })
    }
    return yield* next(e)
  })

  on('session.compact', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    log($, 'session.compact', { agentId: (e as any).agentId, wakeNo: inFlight?.wakeNo })
    return next(e)
  }).catch(($, e, next) => next(e))

  // ---- (e) settlement ----
  on('turn.complete', async ($, e, next) => {
    if (refused) return next(e)
    await ensureBound($)
    const agentId = e.agentId
    if (!agentId) {
      log($, 'turn.complete.main', { reason: e.reason, usage: e.usage })
      return next(e)
    }
    if (!ownAgents.has(agentId)) {
      log($, 'turn.complete.other', { agentId, reason: e.reason, usage: e.usage })
      return next(e)
    }
    const p = inFlight
    const u = (e.usage ?? {}) as Record<string, number>
    const wakeTokens = (u.input_tokens ?? 0) + (u.cache_read_input_tokens ?? 0) + (u.cache_creation_input_tokens ?? 0)
    const stepContext = Math.ceil(wakeTokens / Math.max(stepsThisWake, 1))
    log($, 'turn.complete.branch', {
      agentId,
      wakeNo: p?.wakeNo,
      via: p?.via,
      reason: e.reason,
      usage: e.usage,
      wakeTokens,
      steps: stepsThisWake,
      stepContext,
      elapsedMs: p ? Date.now() - p.startedAt : undefined,
      reportedSeqs: p?.reportedSeqs,
      wake: p?.reason,
      answer: e.answer.slice(0, 400),
    })
    if (stepContext > BRANCH_ROTATE_TOKENS && !rotatePending) {
      // The bound lives here, in the mod, not in an autoCompactWindow setting.
      rotatePending = true
      $.ui.log(`${PLUGIN}: branch context reached ${stepContext} tokens a step (> ${BRANCH_ROTATE_TOKENS}); the next wake opens a fresh branch agent`)
      log($, 'rotate.pending', { wakeNo: p?.wakeNo, wakeTokens, stepContext, branchGeneration })
    }
    if (!p) return next(e)
    inFlight = null
    lastKnownNowMs = Number(await $.clock.now())
    const providerError = e.reason === 'error' || e.reason === 'refusal'
    const noReport = p.reportedSeqs.length === 0
    if (p.granted) await grant($, ['release', generation]).catch(() => {})
    if (providerError || noReport) {
      const verdict = providerLatch.recordFailure()
      if (verdict.armed) {
        $.ui.log(`${PLUGIN}: branch latched off for 5 minutes after ${verdict.streak} consecutive failures; wakes go to main`)
      }
      log($, 'branch.failed', { agentId, wakeNo: p.wakeNo, providerError, noReport, consecutiveErrors: verdict.streak, latchedUntil: verdict.latchedUntil })
      for (const s of p.seqs) handledSeqs.delete(s)
      void $.prompt.submit({ text: `fm-branch-mod: fallback to main - the supervision branch could not handle this wake.\n${p.wakeText}` }).catch(() => {})
    } else {
      providerLatch.recordSuccess()
      // Deterministic captain-class backstop over what the branch just covered.
      await backstopCheck($, p.tasks, p.wakeNo)
    }
    // A branch-absorbed wake must always leave one live cycle behind: if the
    // branch settled a wake and no monitor is armed, arm one here so the next
    // watcher close still reaches a prompt.
    if (!monitorArmed) void armMonitor($, 'branch settled without monitor')
    // Anything that arrived while the branch was busy is still in the queue.
    const scope = await scopeForUnreadWake($, false)
    if (scope.eligibleSeqs.some((s) => !handledSeqs.has(s))) {
      log($, 'wake.requeue', { seqs: scope.eligibleSeqs })
      await routeWake($, rewakeBanner(scope.eligibleSeqs.map((s) => `signal: queued row ${s} (re-scoped after branch settlement)`).join('\n')), 'post-release')
    }
    return next(e)
  }).catch(($, e, next) => next(e))
}
